name: Qiita Slack Notifier

on:
  schedule:
    - cron: "20 23 * * *"  # 毎日 08:10 JST (UTC の 23:10)

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Python をセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: 依存関係をインストール
        run: pip install -r requirements.txt

      - name: Qiita 通知スクリプトを実行
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNELS: ${{ secrets.SLACK_CHANNELS }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AI_SERVICE: ${{ secrets.AI_SERVICE }}
        run: python main.py
